version: '2'
services:

  §§INSTANCE-wordpress:
    image: wordpress:latest
    container_name:  §§INSTANCE-wordpress
    links:
      - §§INSTANCE-wordpress-db:§§INSTANCE-wordpress-db
    ports:
      - "8098:8080"
    depends_on:
      - §§INSTANCE-wordpress-db
      - §§INSTANCE-wordpress-data
    volumes_from: 
      - §§INSTANCE-wordpress-data
    environment: 
       WORDPRESS_DB_HOST: §§INSTANCE-wordpress-db:3306
       WORDPRESS_DB_PASSWORD: §§MYSQL_PASSWORD

  §§INSTANCE-wordpress-db:
    image: mysql
    container_name: §§INSTANCE-wordpress-db
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=§§MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=§§MYSQL_DATABASE
      - MYSQL_USER=§§MYSQL_USER
      - MYSQL_PASSWORD=§§MYSQL_PASSWORD
    volumes_from: 
      - §§INSTANCE-wordpress-data
    depends_on:
      - §§INSTANCE-wordpress-data

  §§INSTANCE-wordpress-data:
    image: busybox
    container_name: §§INSTANCE-wordpress-data
    volumes:
      - §§FOLDER/var/lib/mysql:/var/lib/mysql
      