version: '2'
services:

  wordpress-debug:
    image:  wordpress:latest
    container_name:  wordpress-debug
    links:
      - wordpress-db-debug:wordpress
    ports:
      - "8090:80"
    depends_on:
      - wordpress-db-debug
      - wordpress-data-debug
    volumes_from: 
      - wordpress-data-debug
    environment: 
       WORDPRESS_DB_HOST: wordpress-db-debug:3306
       WORDPRESS_DB_PASSWORD: fenris
       
  wordpress-db-debug:
    image: mysql
    container_name: wordpress-db-debug
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=fenris
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=fenris
    volumes_from: 
      - wordpress-data-debug
    depends_on:
      - wordpress-data-debug

  wordpress-data-debug:
    image: busybox
    container_name: wordpress-data-debug
    volumes:
      - /Users/mue/dockerdata/wordpress/var/lib/mysql:/var/lib/mysql
      8090