version: '3.8'
  
networks:
    bibbox-default-network:
      external: true

services:

  §§INSTANCE-wordpress:
    image: wordpress:latest
    container_name:  §§INSTANCE-wordpress
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - §§INSTANCE-wordpress-db:mysql
    ports:
      - "80"
    depends_on:
      - §§INSTANCE-wordpress-db      
    environment: 
      - WORDPRESS_DB_PASSWORD=§§MYSQL_ROOT_PASSWORD
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_NAME=wordpress
              
  §§INSTANCE-wordpress-db:
    image: mariadb:10.1.21
    container_name: §§INSTANCE-wordpress-db
    restart: unless-stopped
    networks:
      - bibbox-default-network
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=§§MYSQL_ROOT_PASSWORD
    volumes: 
      - ./var/lib/mysql:/var/lib/mysql
      
      
